import Head from 'next/head';
import { BsFillMoonStarsFill }  from "react-icons/bs"
import { AiFillFacebook, AiFillLinkedin,  } from "react-icons/ai"
import Image from "next/image"
import image from "../public/avatar.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
import web6 from "../public/web6.png"
import { useState } from 'react'
import Link from 'next/link'

 

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>NafisBD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white dark:bg-gray-900'>  
        <section className='min-h-screen px-10 md:px-20 lg:px-40'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className=' text-xl font-burtons dark:text-white'>NafisBD._</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=' cursor-pointer text-2xl dark:text-white'/>
              </li>
              <li>
                <a className='text-xl font-burtons bg-gradient-to-r from-cyan-500 to-teal-500  text-white px-4 py-2 border-none rounded-md ml-8 hover:text-black' href="https://nafisbd.com">NafisBD</a>
                </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='font-burtons text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Nafis Mahmud Ayon</h2>
            <h3 className='font-burtons text-2xl py-2 md:text-3xl dark:text-white'>Web Developer and Designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg  mx-auto dark:text-white'>Passionate about UI/UX. Over 3 years of development experience in HTML, CSS, JS, and WordPress frameworks.</p>
          </div>
          <div className='text-5xl flex justify-center gap-10 py-1 text-gray-600 dark:text-white'>
            <AiFillFacebook />
            <AiFillLinkedin />
            
          </div>
          <div className='relative mx-auto mt-20 bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 overflow-hidden md:h-96 md:w-96'>
            <Image src={image} layout="fill" alt="Profile pic" objectFit='cover'/>
          </div>
        </section>

        <section className='px-10 md:px-20 lg:px-40'>
          <div>
            <h3 className='font-burtons text-3xl py-1 dark:text-white'>Service I Offer</h3>
          </div>
          <div>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white'>
              Since the beginning of my journey as a freelance designer and developer. I have done remote work for <span className='text-teal-500'>agencies </span>consulted for <span className='text-teal-500'>startups </span> and collaborated with talented people to create digital products for both business and consumer use.
            </p>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white'>
              I offer from a wide range of services, including brand design, programming and teaching.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={design} width={100} height={100} alt="sds" />
              <h3 className='text-3xl pt-8 pb-2 dark:text-yellow-500'>Beauitiful Designs</h3>
              <p className='text-md mt-2 mb-3 leading-8 py-2 text-gray-800 dark:text-white'>
                Creating elegant designs suited for your needs following core design theory.
              </p>
              <h4 className='text-xl py-4 text-teal-600  '>Design Tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-white'>Adobe Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-white'>Adobe Illustrator</p>
            </div>


            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={code} width={100} height={100} alt="fff" />
              <h3 className='text-3xl pt-8 pb-2 dark:text-yellow-500'>Beauitiful Designs</h3>
              <p className='text-md mt-2 mb-3 leading-8 py-2 text-gray-800 dark:text-white'>
                Creating elegant designs suited for your needs following core design theory.
              </p>
              <h4 className='text-xl py-4 text-teal-600  '>Design Tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-white'>Adobe Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-white'>Adobe Illustrator</p>
            </div>


            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={consulting} width={100} height={100} alt="portfolio" />
              <h3 className='text-3xl pt-8 pb-2 dark:text-yellow-500 '>Beauitiful Designs</h3>
              <p className='text-md mt-2 mb-3 leading-8 py-2 text-gray-800 dark:text-white'>
                Creating elegant designs suited for your needs following core design theory.
              </p>
              <h4 className='text-xl py-4 text-teal-600  '>Design Tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-white'>Adobe Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-white'>Adobe Illustrator</p>
            </div>
          </div>
        </section>

        <section className='px-10 md:px-20 lg:px-40'>
          <div>
          <h3 className='text-3xl py-1 font-burtons dark:text-white'>Portfolio</h3>
          </div>
          <div>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white'>
              Since the beginning of my journey as a freelance designer and developer. I have done remote work for <span className='text-teal-500'>agencies </span>consulted for <span className='text-teal-500'>startups </span> and collaborated with talented people to create digital products for both business and consumer use.
            </p>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white'>
              I offer from a wide range of services, including brand design, programming and teaching.
            </p>
          </div>
          <Link href="/hello"><a>Hello page</a></Link>

          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className=' basis-1/3 flex-1'>
              <Image src={web1} alt="portfolio" className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className=' basis-1/3 flex-1'>
              <Image src={web2} alt="portfolio" className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className=' basis-1/3 flex-1'>
              <Image src={web3} alt="portfolio" className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className=' basis-1/3 flex-1'>
              <Image src={web4} alt="portfolio" className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className=' basis-1/3 flex-1'>
              <Image src={web5} alt="portfolio" className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className=' basis-1/3 flex-1'>
              <Image src={web6} alt="portfolio" className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
          </div>
        </section>
        <footer className='text-center dark:bg-black'>
          <p className='p-5 dark:text-white'>All right reserved by <span><a className='text-l text-yellow-500 hover:text-blue-900' href="https://nafisbd.com">NafisBD</a></span></p>
        </footer>

      </main>

    </div>
  );
}
